---
- name: Install htop
  hosts: all
  become: yes
  roles: 
    - role: hello_role
      vars:
        role_message: "Hello!"
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install htop
      apt:
        name: htop
        state: present